### ISSUE TITLE
add types for the react components

### ISSUE THREAD

**Issue by SoftMngBHD** [roblburris/image-ml#2]
do you think we should add types for the react frontend regarding state and props. it might speed up dev in the future and allows for better autocomplete. should be easy to add with simple interfaces and could have a huge influence.

**Comment by Eesha-Jain** [comment]
Both work for me!

**Comment by Nv7-GitHub** [comment]
Yes

**Comment by SoftMngBHD** [comment]
okay i can take care of this this weekend or later, provided robert aproves it.

**Comment by roblburris** [comment]
Go for it! Making things more typesafe is always a good practice :)
